language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd exam_2
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam_2/build
  on:
    branch:
      - master
      - exam_2
      - devel
